import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import DelugeRPC from "deluge-rpc";

const Card = ({ cardInfo }) => {
  return (
    <a className={styles.card}>
      <header>
        <h2>{cardInfo.title}</h2>
        <Image src={cardInfo.imagePath} width={50} height={50}></Image>
      </header>
      <p>Current down speed: {cardInfo.details} Mbps</p>
    </a>
  );
};

export default function Home({ deluge }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{" "}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <Card cardInfo={deluge}></Card>
        </div>
      </main>
    </div>
  );
}

export async function getServerSideProps(context) {
  const delugerpc = new DelugeRPC("http://192.168.0.165:8112/", "thunderbutt");

  const methods = await delugerpc.call("system.listMethods");
  console.log(methods);

  const deet = await delugerpc.connect(0);

  const deluge = {
    title: "Deluge",
    imagePath: "/deluge.png",
    isUp: true,
    details: deet,
  };

  return {
    props: { deluge },
  };
}
